@startuml

skinparam packageStyle rectangle

package main.view {
  class MainMenu {
    field1
    method1()
  }
  class WorkoutMenu {
    field1
    method1()
  }
}

package main.model {
  class WorkoutModel {
    field1
    method1()
  }
}

package main.controller {
  class GUIController {
    field1
    method1()
  }
}

@enduml